name: Release flow
on:
  release:
    types: [created]

jobs:
  publish:
    name: 📦 Publish 📦
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
      - name: Cache .pnpm-store # From https://pnpm.io/continuous-integration
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: pnpm install
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
